module.exports = {
	plugins: ['@namics/stylelint-bem', 'stylelint-order'],
	rules: {
		'at-rule-empty-line-before': [
			'always',
			{
				ignore: ['first-nested'],
			},
		],
		'at-rule-name-space-after': 'always',
		'at-rule-no-unknown': [ 
			true, 
			{	
				ignoreAtRules: [
					'value'
				], 
			}, 
		],
		'block-closing-brace-newline-before': 'always',
		'block-opening-brace-newline-after': 'always',
		'block-opening-brace-space-before': 'always',
		'block-no-empty': true,
		'color-no-invalid-hex': true,
		'comment-no-empty': true,
		'comment-empty-line-before': 'always', 
		'declaration-block-no-duplicate-properties': [
			true,
			{
				ignore: ['consecutive-duplicates-with-different-values'],
			},
		],
		'declaration-block-no-shorthand-property-overrides': true,
		'font-family-no-duplicate-names': true,
		'font-family-no-missing-generic-family-keyword': true,
		'function-calc-no-invalid': true,
		'function-calc-no-unspaced-operator': true,
		'function-comma-space-after': 'always',
		'function-linear-gradient-no-nonstandard-direction': true,
		'indentation': 'tab',
		'keyframe-declaration-no-important': true,
		'max-empty-lines': 1,
		'media-feature-name-no-unknown': true,
		'no-descending-specificity': true,
		'no-duplicate-at-import-rules': true,
		'no-duplicate-selectors': true,
		'no-empty-first-line': true,
		'no-empty-source': true,
		'no-extra-semicolons': true,
		'no-invalid-double-slash-comments': true,
		'number-max-precision': 3,
		'order/properties-order': [
			'content',
			'quotes',
			'display',
			'visibility',
			'position',
			'z-index',
			'top',
			'right',
			'bottom',
			'left',
			'box-sizing',
			'grid',
			'grid-after',
			'grid-area',
			'grid-auto-columns',
			'grid-auto-flow',
			'grid-auto-rows',
			'grid-before',
			'grid-column',
			'grid-column-end',
			'grid-column-gap',
			'grid-column-start',
			'grid-columns',
			'grid-end',
			'grid-gap',
			'grid-row',
			'grid-row-end',
			'grid-row-gap',
			'grid-row-start',
			'grid-rows',
			'grid-start',
			'grid-template',
			'grid-template-areas',
			'grid-template-columns',
			'grid-template-rows',
			'flex',
			'flex-basis',
			'flex-direction',
			'flex-flow',
			'flex-grow',
			'flex-shrink',
			'flex-wrap',
			'align-content',
			'align-items',
			'align-self',
			'justify-content',
			'order',
			'width',
			'min-width',
			'max-width',
			'height',
			'min-height',
			'max-height',
			'margin',
			'margin-top',
			'margin-right',
			'margin-bottom',
			'margin-left',
			'padding',
			'padding-top',
			'padding-right',
			'padding-bottom',
			'padding-left',
			'float',
			'clear',
			'overflow',
			'overflow-x',
			'overflow-y',
			'clip',
			'zoom',
			'columns',
			'column-gap',
			'column-fill',
			'column-rule',
			'column-span',
			'column-count',
			'column-width',
			'table-layout',
			'empty-cells',
			'caption-side',
			'border-spacing',
			'border-collapse',
			'list-style',
			'list-style-position',
			'list-style-type',
			'list-style-image',
			'transform',
			'transform-box',
			'transform-origin',
			'transform-style',
			'backface-visibility',
			'perspective',
			'perspective-origin',
			'transition',
			'transition-property',
			'transition-duration',
			'transition-timing-function',
			'transition-delay',
			'animation',
			'animation-name',
			'animation-duration',
			'animation-play-state',
			'animation-timing-function',
			'animation-delay',
			'animation-iteration-count',
			'animation-direction',
			'border',
			'border-top',
			'border-right',
			'border-bottom',
			'border-left',
			'border-width',
			'border-top-width',
			'border-right-width',
			'border-bottom-width',
			'border-left-width',
			'border-style',
			'border-top-style',
			'border-right-style',
			'border-bottom-style',
			'border-left-style',
			'border-radius',
			'border-top-left-radius',
			'border-top-right-radius',
			'border-bottom-right-radius',
			'border-bottom-left-radius',
			'border-color',
			'border-top-color',
			'border-right-color',
			'border-bottom-color',
			'border-left-color',
			'outline',
			'outline-color',
			'outline-offset',
			'outline-style',
			'outline-width',
			'stroke-width',
			'stroke-linecap',
			'stroke-dasharray',
			'stroke-dashoffset',
			'stroke',
			'opacity',
			'background',
			'background-attachment',
			'background-clip',
			'background-color',
			'background-image',
			'background-repeat',
			'background-position',
			'background-size',
			'box-shadow',
			'fill',
			'color',
			'font',
			'font-family',
			'font-size',
			'font-size-adjust',
			'font-smoothing',
			'font-stretch',
			'font-style',
			'font-variant',
			'font-weight',
			'font-emphasize',
			'font-emphasize-position',
			'font-emphasize-style',
			'letter-spacing',
			'line-height',
			'list-style',
			'text-align',
			'text-align-last',
			'text-decoration',
			'text-decoration-color',
			'text-decoration-line',
			'text-decoration-style',
			'text-indent',
			'text-justify',
			'text-overflow',
			'text-overflow-ellipsis',
			'text-overflow-mode',
			'text-rendering',
			'text-outline',
			'text-shadow',
			'text-transform',
			'text-wrap',
			'word-wrap',
			'word-break',
			'text-emphasis',
			'text-emphasis-color',
			'text-emphasis-style',
			'text-emphasis-position',
			'vertical-align',
			'white-space',
			'word-spacing',
			'hyphens',
			'src',
			'tab-size',
			'counter-reset',
			'counter-increment',
			'resize',
			'cursor',
			'pointer-events',
			'speak',
			'user-select',
			'nav-index',
			'nav-up',
			'nav-right',
			'nav-down',
			'nav-left',
		],
		'property-no-unknown': [
			true,
			{
				ignoreProperties: ['composes', 'compose-with'],
				ignoreSelectors: [':export', '/^:import/'],
			},
		],
		'rule-empty-line-before': [
			'always',
			{
				ignore: ['first-nested'],
			}
		],
		'selector-combinator-space-after': 'always',
		'selector-combinator-space-before': 'always',
		'selector-pseudo-class-no-unknown': [
			true,
			{
				ignorePseudoClasses: [
					'export',
					'import',
					'global',
					'local',
					'external',
				],
			},
		],
		'selector-pseudo-element-no-unknown': true,
		'selector-type-no-unknown': [
			true,
			{
				ignoreTypes: ['from'],
			},
		],
		'shorthand-property-no-redundant-values': true,
		'string-no-newline': true,
		'unit-no-unknown': true,
	},
	ignoreFiles: [
        '**/*.ts',
        '**/*.tsx',
    ]
}
